// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD28R6sjJcQy3mZQ6W9ME1YFCGe5bYUPYU',
    appId: '1:807473502832:web:87771f620c0d2f100272b5',
    messagingSenderId: '807473502832',
    projectId: 'finkost-7868a',
    authDomain: 'finkost-7868a.firebaseapp.com',
    storageBucket: 'finkost-7868a.firebasestorage.app',
    measurementId: 'G-BMRENJT3S2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkZ3cENNGKiHFNg0iCwLcHhbZKFbsmDPE',
    appId: '1:807473502832:android:565ae10016c8954e0272b5',
    messagingSenderId: '807473502832',
    projectId: 'finkost-7868a',
    storageBucket: 'finkost-7868a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5QUbH0xSid5Adgqfo7E-tZbjT3H31v2I',
    appId: '1:807473502832:ios:548e7d94918ef7d10272b5',
    messagingSenderId: '807473502832',
    projectId: 'finkost-7868a',
    storageBucket: 'finkost-7868a.firebasestorage.app',
    iosBundleId: 'com.example.finkost',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5QUbH0xSid5Adgqfo7E-tZbjT3H31v2I',
    appId: '1:807473502832:ios:548e7d94918ef7d10272b5',
    messagingSenderId: '807473502832',
    projectId: 'finkost-7868a',
    storageBucket: 'finkost-7868a.firebasestorage.app',
    iosBundleId: 'com.example.finkost',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD28R6sjJcQy3mZQ6W9ME1YFCGe5bYUPYU',
    appId: '1:807473502832:web:c391d6c65133fe0b0272b5',
    messagingSenderId: '807473502832',
    projectId: 'finkost-7868a',
    authDomain: 'finkost-7868a.firebaseapp.com',
    storageBucket: 'finkost-7868a.firebasestorage.app',
    measurementId: 'G-BK0ZEP3GLD',
  );

}